**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

**Splitting Array**

In [2]:
import numpy as np
a = np.arange(20)
print('First array')
print(a)
print('\n')
print('Splitting the array in 2 equal size array')
b = np.split(a,2)
print(b)
print('\n')

First array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Splitting the array in 2 equal size array
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]




In [3]:
a=np.arange(10)
#splitting the array indicated first at 3, second 5, 3rd on 9
print('splitting the array indicated first at 3, second 5 and remaining in 3rd')
c=np.split(a,[3,5,9])
print(c)
print('\n')

splitting the array indicated first at 3, second 5 and remaining in 3rd
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([9])]




In [4]:
a=np.arange(9)
#splitting the array indicated first at 4, second 5- 7 remaining in 3rd
print('splitting the array indicated first at 3, second 5 and remaining in 3rd')
c=np.split(a,[2,3,5])
print(c)
print('\n')

splitting the array indicated first at 3, second 5 and remaining in 3rd
[array([0, 1]), array([2]), array([3, 4]), array([5, 6, 7, 8])]




In [5]:
a=np.arange(9)
#splitting the array indicated first at 4, second 5- 7 remaining in 3rd
print('splitting the array indicated first at 3, second 5 and remaining in 3rd')
c=np.split(a,(2,3,5))
print(c)
print('\n')

splitting the array indicated first at 3, second 5 and remaining in 3rd
[array([0, 1]), array([2]), array([3, 4]), array([5, 6, 7, 8])]




In [11]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Data types for ndarray**

In [12]:
array1 =np.array([3,4,5],dtype=float)
array1

array([3., 4., 5.])

In [13]:
array1 =np.array([3,4,5],dtype=np.float64)
array1

array([3., 4., 5.])

In [14]:
array1.dtype

dtype('float64')

In [16]:
array = np.array([1,2,3,4,5])

In [18]:
array.dtype

dtype('int64')

In [17]:
array.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [11]:
arr1 = np.array(['2.3','5.6','3.55'],dtype=np.bytes_)
arr1.dtype

dtype('S4')

In [12]:
arr1

array([b'2.3', b'5.6', b'3.55'], dtype='|S4')

In [6]:
array2 = np.array([3.5, 4.6, 5.5], dtype = np.int32)
array2

array([3, 4, 5], dtype=int32)

In [13]:
arr1.dtype

dtype('S4')

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2.dtype

dtype('int32')

In [14]:
l=[2,3,4]
type(l)

list

In [15]:
type(arr1)

numpy.ndarray

In [16]:
s='6778.88'
float(s)

6778.88

In [17]:
n='300000'
int(n)

300000

In [18]:
s='6.7'
float(s)

6.7

In [19]:
s='6.78999'
float(s)

6.78999

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr*0.005

array([[0.005, 0.01 , 0.015],
       [0.02 , 0.025, 0.03 ]])

In [26]:
%time arr**2

CPU times: total: 15.6 ms
Wall time: 40.2 ms


array([[ 1,  4,  9],
       [16, 25, 36]])

**Comparison of Array**

In [33]:
arr2 = np.array([[3,4,5],[4,5,6]])
arr2

array([[3, 4, 5],
       [4, 5, 6]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2>arr

array([[ True,  True,  True],
       [False, False, False]])

In [36]:
arr2<arr

array([[False, False, False],
       [False, False, False]])

In [37]:
7<6

False

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr<=4

array([[ True,  True,  True],
       [ True, False, False]])

**One dimensional Indexing**

In [40]:
arr = np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [41]:
arr[0]

np.int64(10)

In [42]:
arr[-3]

np.int64(50)

In [44]:
arr[6]

np.int64(70)

In [ ]:
arr[7]

IndexError: index 7 is out of bounds for axis 0 with size 7

In [46]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
arr2d[:-2]

array([[10, 20, 30]])

In [50]:
print(arr2d[0,0])

10


In [51]:
arr2d = np.arange(1,21).reshape(5,4)

In [52]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [53]:
arr2d[1:-1,1:-1]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

**SLice this array [[10,11,12],[14,15,16],[18,19,20]] from above**

In [61]:
arr2d[::2,::2]

array([[ 1,  3],
       [ 9, 11],
       [17, 19]])

**SLice this array [[1,3],[9,11],[17,19]] from above**

In [60]:
arr2d[2:,2:]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [63]:
arr1 = np.array([12,13,14,15,16,17])
arr1

array([12, 13, 14, 15, 16, 17])

In [64]:
arr2=arr1

In [65]:
arr2

array([12, 13, 14, 15, 16, 17])

In [66]:
arr2[3:5]

array([15, 16])

In [68]:
arr2[3:5]=20
arr2[3:5]

array([20, 20])

In [69]:
arr2d = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [70]:
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [71]:
arr2d[:-2]

array([[10, 20, 30]])

In [73]:
arr[1:,2:3]

array([[16],
       [20]])

In [74]:
arr[1:,1:2]

array([[15],
       [19]])

In [75]:
arr[:2,]

array([[10, 11, 12],
       [14, 15, 16]])

84. Write a program to apply scalar arithmetic operations on a NumPy array
• Perform addition, subtraction, multiplication, and division with scalars.
• Understand how operations are broadcast across the array.
• Predict element-wise results for each operation.

In [76]:
import numpy as np

a = np.array([10, 20, 30, 40])

print("Original Array:", a)

print("Addition:", a + 5)
print("Subtraction:", a - 5)
print("Multiplication:", a * 5)
print("Division:", a / 5)

Original Array: [10 20 30 40]
Addition: [15 25 35 45]
Subtraction: [ 5 15 25 35]
Multiplication: [ 50 100 150 200]
Division: [2. 4. 6. 8.]


85. Write a program to perform element-wise arithmetic between two arrays
• Use +, -, *, / operators between same-shaped arrays.
• Understand and apply broadcasting rules.
• Visualize how array shapes influence operations.

In [77]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Array A:", a)
print("Array B:", b)

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Array A: [10 20 30]
Array B: [2 4 5]
Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


86. Write a program to perform arithmetic with multidimensional arrays using
broadcasting
• Create 2D arrays and apply element-wise operations.
• Validate shape compatibility for operations.
• Learn to generalize scalar operations to higher dimensions.
Universal and Mathematical Functions

In [78]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print("Array A:")
print(a)

print("Array B:", b)

print("Addition:")
print(a + b)

print("Multiplication:")
print(a * b)

Array A:
[[1 2 3]
 [4 5 6]]
Array B: [10 20 30]
Addition:
[[11 22 33]
 [14 25 36]]
Multiplication:
[[ 10  40  90]
 [ 40 100 180]]


87. Write a program to apply NumPy’s sin(), sqrt(), and log() on arrays
• Use ufuncs for element-wise mathematical transformations.
• Understand the input-output behavior of sin(), log(), and sqrt().
• Compare original and transformed arrays.

In [81]:
import numpy as np

a = np.array([1, 4, 9, 16])

print("Original Array:", a)

print("Square Root:", np.sqrt(a))
print("Sine:", np.sin(a))
print("Log:", np.log(a))

Original Array: [ 1  4  9 16]
Square Root: [1. 2. 3. 4.]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Log: [0.         1.38629436 2.19722458 2.77258872]


88. Write a program to multiply an array with a ufunc result (e.g., array *
sin(array))
• Combine arrays and ufunc results for advanced element-wise operations.
• Chain ufuncs in expressions.
• Visualize how mathematical functions modify array data.

In [82]:
import numpy as np

a = np.array([1, 2, 3, 4])

print("Original Array:", a)

result = a * np.sin(a)

print("Sin of Array:", np.sin(a))
print("Array * Sin(Array):", result)

Original Array: [1 2 3 4]
Sin of Array: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Array * Sin(Array): [ 0.84147098  1.81859485  0.42336002 -3.02720998]
