**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
a = np.array([[1, 2, 3]])

In [6]:
a.shape

(1, 3)

In [7]:
a.dtype

dtype('int64')

In [9]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [11]:
b.dtype

dtype('int64')

In [12]:
b.ndim

2

In [13]:
b.size

6

In [14]:
b.shape

(2, 3)

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros((0,3, 2))

array([], shape=(0, 3, 2), dtype=float64)

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [26]:
#array of all odd numbers from 0 to 20
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [27]:
np.arange(1,20,2).reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.random.random(3)

array([0.21839854, 0.54618701, 0.60540974])

In [32]:
np.random.random((3, 4))

array([[0.06052059, 0.48968847, 0.41938578, 0.22980187],
       [0.3972947 , 0.38244498, 0.19451112, 0.32827753],
       [0.57266704, 0.27227953, 0.79632888, 0.3926629 ]])

**Arithmetic Operation**

In [33]:
a = np.arange(4)

In [34]:
a

array([0, 1, 2, 3])

In [36]:
a+4

array([4, 5, 6, 7])

In [37]:
a*2

array([0, 2, 4, 6])

In [35]:
b = np.arange(4)

In [38]:
b

array([0, 1, 2, 3])

In [39]:
a+b

array([0, 2, 4, 6])

In [40]:
a-b

array([0, 0, 0, 0])

In [41]:
a*b

array([0, 1, 4, 9])