**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

Numpy

In [3]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr)

[0 1 2 3 4 5]


Numpy gives tremendous perfomance deference

In [4]:
a = gives

NameError: name 'gives' is not defined

In [5]:
a = range(0,20)
print(type(a))
list(a)

<class 'range'>


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [26]:
import numpy as np
an_arr=np.arange(20)
print(type(an_arr))
print(an_arr)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
import numpy as np
an_arr = np.arange(1000) #array
a_list = list(range(1000)) #list

In [ ]:
#a_list

In [9]:
%time for x in range(100000):an_arr2 = an_arr **2

CPU times: total: 125 ms
Wall time: 130 ms


In [ ]:
#an_arr2

In [11]:
%time for i in range(100000):a_list2 = [x**2 for x in a_list]

CPU times: total: 3.2 s
Wall time: 3.37 s


In [14]:
list1 = [2,4,8,7]
list1*5

[2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7]

In [15]:
list1+list1

[2, 4, 8, 7, 2, 4, 8, 7]

In [17]:
a = np.array(list1)
a*5

array([10, 20, 40, 35])

In [19]:
import numpy as np
list1=[2,3,4,5,7,8]
arr1=np.array(list1)
#arr1.dtype.int16
print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

8
6
int64
[2 3 4 5 7 8]


In [37]:
import numpy as np
list1=[2,3,4,5,7,8]
arr1=np.array(list1)

print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

arr1.dtype=np.int16
print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

8
6
int64
[2 3 4 5 7 8]
2
24
int16
[2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 7 0 0 0 8 0 0 0]


C:\Users\hppc\AppData\Local\Temp\ipykernel_14056\188054680.py:10: DeprecationWarning: Setting the dtype on a NumPy array has been deprecated in NumPy 2.5.
Instead of changing the dtype on an array x, create a new array with x.view(new_dtype)
  arr1.dtype=np.int16


In [47]:
arr1=[2,3,4,5,7,8]

In [40]:
arr1*2

[2, 3, 4, 5, 7, 8, 2, 3, 4, 5, 7, 8]

In [41]:
arr1=np.arange(10)
print(arr1.dtype)

int64


In [42]:
print(type(arr1))

<class 'numpy.ndarray'>


In [45]:
arr1+arr1

[2, 3, 4, 5, 7, 8, 2, 3, 4, 5, 7, 8]

In [53]:
arr1 = [2,3,4,5,7,8]


In [3]:
arr1 = [2, 3, 4, 5, 7, 8]

result = [x * x for x in arr1]
print(result)

[4, 9, 16, 25, 49, 64]


In [ ]:
import numpy as np

arr1 = np.array([2, 3, 4, 5, 7, 8])

print(arr1 * arr1)

[ 4  9 16 25 49 64]
[0 0 0 0 0 0]


In [2]:
print(arr1 - arr1)

[0 0 0 0 0 0]


In [4]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
import numpy as np
arr1=np.empty((5,3,2))

In [6]:
arr1

array([[[1.31644546e-311, 1.02271589e-321],
        [0.00000000e+000, 0.00000000e+000],
        [1.42413554e-306, 5.02034658e+175]],

       [[5.40725488e-038, 5.98730606e+174],
        [4.49949992e+174, 1.50400124e+161],
        [4.46596656e-062, 4.26032253e-096]],

       [[1.12855837e+277, 8.76730979e+252],
        [2.59027914e-144, 3.80985069e+180],
        [1.14428494e+243, 2.59027907e-144]],

       [[7.79952704e-143, 2.08968289e-076],
        [1.71830036e+185, 2.61887125e+180],
        [1.45298805e-051, 2.59027862e-144]],

       [[2.59903818e-144, 7.42138030e-091],
        [5.65042638e-038, 4.17824707e-062],
        [1.11475752e+261, 1.16318408e-028]]])

In [11]:
arr1=np.empty((1,2, 3, 2,2))
arr1

array([[[[[6.23042070e-307, 4.67296746e-307],
          [1.69121096e-306, 1.42419938e-306]],

         [[1.42413555e-306, 1.78019082e-306],
          [1.37959740e-306, 6.23057349e-307]],

         [[1.06811422e-306, 1.42417221e-306],
          [1.37961641e-306, 1.60220393e-306]]],


        [[[8.34424342e-308, 1.22382882e-307],
          [1.11258854e-306, 1.11261502e-306]],

         [[1.42410839e-306, 7.56597770e-307],
          [6.23059726e-307, 1.42419530e-306]],

         [[6.89805151e-307, 1.78020169e-306],
          [1.42410974e-306, 8.91238233e-313]]]]])

In [10]:
arr1.shape

(1, 2, 3, 2, 3)

In [12]:
import numpy as np
data = np.random.randn(3,3)
data

array([[ 0.28169065,  0.65954653, -0.85829028],
       [ 1.61810763, -1.99593604,  0.18273757],
       [-0.10459112,  0.49755672,  0.51297907]])

In [13]:
np.random.randn(2,3,2)

array([[[-0.25693541, -1.61712429],
        [-0.471223  ,  0.15489902],
        [-0.688455  , -0.65688962]],

       [[-0.90530979,  0.49109757],
        [ 0.10947678, -1.7880892 ],
        [-1.3392038 ,  1.30180319]]])

In [15]:
a = np.array([[0,1,2],[4,5,6]])
a

array([[0, 1, 2],
       [4, 5, 6]])

In [17]:
a = np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.random.randint(0,3)

2

In [19]:
np.random.randint(1,9)

8

**Array of random number**

In [20]:
np.random.randint(10,20,(3,1,3))

array([[[18, 14, 10]],

       [[16, 16, 15]],

       [[17, 18, 19]]], dtype=int32)

**Array create function**

**Combinning ndarray**

**Vertical Stack**

In [2]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [3]:
arr1+arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
arr3 = np.vstack((arr1,arr2))
print(arr3)

print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


**Horizontal stack**

In [5]:
import numpy as np
arr3 = np.hstack((arr1,arr2))
print(arr3)

print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


**concating ndarray**