**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

**Broadcasting Basics**

113. Write a program to apply broadcasting between a 2D and 1D array
• Use broadcasting to apply operations on arrays of different shapes.
• Understand NumPy's broadcasting rules (same or size-1 dimensions).
• Predict result shapes after operations like A + b.

In [1]:
import numpy as np

In [8]:
A = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([10, 20, 30])

result = A + b

print("A shape:", A.shape)
print("b shape:", b.shape)
print("Result:" )
print(result)
print("Result shape:", result.shape)

A shape: (2, 3)
b shape: (3,)
Result:
[[11 22 33]
 [14 25 36]]
Result shape: (2, 3)


114. Write a program to broadcast a 1D row vector across a 2D matrix
• Understand how NumPy expands smaller arrays to match larger ones.
• Practice horizontal/vertical broadcasting operations.
• Apply broadcasting rules to addition, multiplication, etc.

In [9]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])

row = np.array([10, 20, 30])

addition = matrix + row
multiplication = matrix * row

print("Addition:")
print(addition)

print("Multiplication:")
print(multiplication)

Addition:
[[11 22 33]
 [14 25 36]]
Multiplication:
[[ 10  40  90]
 [ 40 100 180]]


**Advanced Broadcasting with Higher Dimensions**

115. Write a program to multiply two 3D arrays using complex broadcasting
• Reshape arrays to (3,1,2) and (3,2,1) and apply broadcasting.
• Understand compatibility conditions for higher-dimensional arrays.
• Visualize resulting 3D array after broadcasting multiplication.

In [ ]:
A = np.arange(6).reshape(3, 1, 2)
B = np.arange(6).reshape(3, 2, 1)

result = A * B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("Result shape:", result)
print("Result:")
print(result)

A shape: (3, 1, 2)
B shape: (3, 2, 1)
Result shape: (3, 2, 2)
Result:
[[[ 0  0]
  [ 0  1]]

 [[ 4  6]
  [ 6  9]]

 [[16 20]
  [20 25]]]


116. Write a program to verify broadcasting compatibility rules for mismatched
shapes
• Apply Rule 1: Insert 1 in missing dimensions.
• Apply Rule 2: Replicate along dimensions of size 1.
• Test and resolve shape mismatch errors in real use cases.

In [11]:
A = np.ones((2, 3))
B = np.ones((3,))

try:
    result = A + B
    print("Compatible")
    print("Result shape:", result.shape)
except ValueError:
    print("Not compatible")

# Mismatched example
C = np.ones((2, 3))
D = np.ones((2,))

try:
    result = C + D
    print("Compatible")
    print("Result shape:", result.shape)
except ValueError:
    print("Not compatible: Shape mismatch")

Compatible
Result shape: (2, 3)
Not compatible: Shape mismatch


**Creating Series from Various Sources**

117. Write a program to create a Series from a list with and without custom index
• Create a basic Series using a list of numeric values.
• Apply custom labels as index instead of default integer index.
• Interpret the string representation of a Series.

In [13]:
import pandas as pd

data = [10, 20, 30, 40]

# Without custom index
s1 = pd.Series(data)

# With custom index
s2 = pd.Series(data, index=['A', 'B', 'C', 'D'])

print("Series without custom index:")
print(s1)

print("\nSeries with custom index:")
print(s2)

Series without custom index:
0    10
1    20
2    30
3    40
dtype: int64

Series with custom index:
A    10
B    20
C    30
D    40
dtype: int64


118. Write a program to create a Series from a NumPy array and verify data linkage
• Convert a NumPy array into a pandas Series.
• Observe dynamic linking between original array and Series.
• Understand mutability and reference behavior.

In [23]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30, 40])

s = pd.Series(arr, copy=False)

print("Original NumPy array:")
print(arr)

print("\nOriginal Series:")
print(s)

arr[0] = 100

print("\nAfter changing NumPy array:")
print(arr)

print("\nSeries after changing NumPy array:")
print(s)

Original NumPy array:
[10 20 30 40]

Original Series:
0    10
1    20
2    30
3    40
dtype: int64

After changing NumPy array:
[100  20  30  40]

Series after changing NumPy array:
0    100
1     20
2     30
3     40
dtype: int64


119. Write a program to create a Series from a dictionary with custom index
• Use dictionary key-value pairs to form Series index and data.
• Handle missing keys using an index list (introducing NaN).
• Understand auto-alignment of labels and handling of missing data.

In [27]:
import pandas as pd

data = {
    'Laptop': 50000,
    'Desktop': 20000,
    'Tablet': 30000,
    'Smartphone': 40000
}

s = pd.Series(data, index=['Laptop', 'Desktop', 'Tablet', 'Smartphone'])  

print(s)

Laptop        50000
Desktop       20000
Tablet        30000
Smartphone    40000
dtype: int64


In [26]:
import pandas as pd
marks = np.array([75, 85, 90, 95, 80])
series = pd.Series(marks, index=['Math', 'Science', 'English', 'History', 'Art'])
print(series)

Math       75
Science    85
English    90
History    95
Art        80
dtype: int64


In [30]:
import pandas as pd
marks = pd.Series([75, 85, 90, 95, 80],
                  index=['Niyati', 'Aarav', 'Riya', 'Kabir', 'Anaya'])

print("Original Series:")
print(marks)

print("\nMarks of Niyati:", marks['Niyati'])
print("\nMarks of 3rd student:", marks.iloc[2])
print("\nMarks of First three students:", marks.iloc[:3])
print("\nMarks of Aarav and Kabir :",marks[['Aarav', 'Kabir']])

Original Series:
Niyati    75
Aarav     85
Riya      90
Kabir     95
Anaya     80
dtype: int64

Marks of Niyati: 75

Marks of 3rd student: 90

Marks of First three students: Niyati    75
Aarav     85
Riya      90
dtype: int64

Marks of Aarav and Kabir : Aarav    85
Kabir    95
dtype: int64


In [38]:
import pandas as pd
stock = pd.Series([50000, 20000, 30000, 40000],
                  index=['Laptop', 'Desktop', 'Tablet', 'Smartphone'])

print("Original stock")
print(stock)

stock['Laptop'] = 55000
stock.iloc[1] = 25000

stock[['Tablet', 'Smartphone']] = stock[['Tablet', 'Smartphone']] + 1000

print("\nUpdated stock")
print(stock)

Original stock
Laptop        50000
Desktop       20000
Tablet        30000
Smartphone    40000
dtype: int64

Updated stock
Laptop        55000
Desktop       25000
Tablet        31000
Smartphone    41000
dtype: int64


In [43]:
import pandas as pd
scores = pd.Series([75, 85, 90, 95, 80 , 65 , 84 ],
                   index=['Niyati', 'Nisha', 'Mira', 'Krina', 'Mahi', 'Diya', 'Aesha'])

print("Scores greater than 80:")
print(scores[scores > 80])

print("Scores between 60 and 80:")
print(scores[(scores >= 60) & (scores <= 85)])

print("Scores between 70 and 90 :")
print(scores[(scores >= 70) & (scores <= 90)])

Scores greater than 80:
Nisha    85
Mira     90
Krina    95
Aesha    84
dtype: int64
Scores between 60 and 80:
Niyati    75
Nisha     85
Mahi      80
Diya      65
Aesha     84
dtype: int64
Scores between 70 and 90 :
Niyati    75
Nisha     85
Mira      90
Mahi      80
Aesha     84
dtype: int64


In [48]:
import pandas as pd
import numpy as np

sales = pd.Series([12,45,78,96,78,56,64],
                    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

print("Orriginal Sales Data : ")
print(sales)

print("Sales After adding 5 :")
print(sales + 5)

print("Sales After dividing by 2 :")
print(sales / 2)

print("Sales root square :")
print(np.sqrt(sales))

Orriginal Sales Data : 
Mon    12
Tue    45
Wed    78
Thu    96
Fri    78
Sat    56
Sun    64
dtype: int64
Sales After adding 5 :
Mon     17
Tue     50
Wed     83
Thu    101
Fri     83
Sat     61
Sun     69
dtype: int64
Sales After dividing by 2 :
Mon     6.0
Tue    22.5
Wed    39.0
Thu    48.0
Fri    39.0
Sat    28.0
Sun    32.0
dtype: float64
Sales root square :
Mon    3.464102
Tue    6.708204
Wed    8.831761
Thu    9.797959
Fri    8.831761
Sat    7.483315
Sun    8.000000
dtype: float64


In [49]:
import pandas as pd
sales = pd.Series([12,45,78,96,78,56,64])

print("Unique Sales quantities :")
print(sales.unique())

print("Frequency of each sales quantity :")
print(sales.value_counts())

print("Most frequently occurring sales quantity :")
print(sales.value_counts().idxmax())

Unique Sales quantities :
[12 45 78 96 56 64]
Frequency of each sales quantity :
78    2
12    1
45    1
96    1
56    1
64    1
Name: count, dtype: int64
Most frequently occurring sales quantity :
78
