**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

Intrinsic Creation of an Array

In [2]:
import numpy as np

In [16]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [7]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [8]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.random.random((3,3))

array([[0.65201419, 0.08629509, 0.57463125],
       [0.97910645, 0.35431484, 0.3486049 ],
       [0.70066758, 0.22000345, 0.89817336]])

In [17]:
np.random.random(3)

array([0.37703263, 0.18575991, 0.02478841])

Arithmetic with NumPy Arrays

In [18]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a+4

array([4, 5, 6, 7])

In [22]:
a*2

array([0, 2, 4, 6])

In [23]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [24]:
a+b

array([ 4,  6,  8, 10])

In [25]:
a-b

array([-4, -4, -4, -4])

In [26]:
a*b

array([ 0,  5, 12, 21])

In [27]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [28]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [29]:
A = np.arange(0, 9).reshape(3, 3)

In [30]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

The Matrix Product

In [33]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [34]:
A.dot(A)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [35]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [36]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [38]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [39]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [40]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [41]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Aggregate Function

In [42]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])

In [43]:
a.sum()

np.float64(15.0)

In [44]:
a.min()

np.float64(0.3)

In [45]:
a.max()

np.float64(5.7)

In [46]:
a.mean()

np.float64(3.0)

In [47]:
a.std()

np.float64(2.0079840636817816)

Iterating an Array

In [48]:
for i in a:
    print(i)

3.3
4.5
1.2
5.7
0.3


In [49]:
for row in A:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [50]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [51]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([3., 4., 5.])

In [52]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([1., 4., 7.])

In [53]:
def func(x):
    return x/2

In [54]:
np.apply_along_axis(func, axis=1, arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [55]:
np.apply_along_axis(func, axis=0, arr=A)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

Conditions and Boolean Arrays

In [56]:
A = np.random.random((4, 4))

In [57]:
A

array([[0.9769471 , 0.98968228, 0.27866514, 0.66632012],
       [0.05628074, 0.46020274, 0.31114742, 0.51064036],
       [0.67772862, 0.14258001, 0.13854245, 0.24988313],
       [0.56170145, 0.78362799, 0.99949943, 0.60345274]])

In [58]:
A < 0.5

array([[False, False,  True, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [59]:
A[A < 0.5]

array([0.27866514, 0.05628074, 0.46020274, 0.31114742, 0.14258001,
       0.13854245, 0.24988313])

Shape Manipulation

In [60]:
a = np.random.random(12)

In [61]:
a

array([0.53110643, 0.35485197, 0.65073548, 0.72898392, 0.70117184,
       0.56355797, 0.7482217 , 0.1451689 , 0.9994954 , 0.42161074,
       0.09843173, 0.29838017])

In [62]:
A = a.reshape(3, 4)
A

array([[0.53110643, 0.35485197, 0.65073548, 0.72898392],
       [0.70117184, 0.56355797, 0.7482217 , 0.1451689 ],
       [0.9994954 , 0.42161074, 0.09843173, 0.29838017]])

In [63]:
a.shape = (3, 4)
a

C:\Users\hppc\AppData\Local\Temp\ipykernel_5128\476674851.py:1: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (3, 4)


array([[0.53110643, 0.35485197, 0.65073548, 0.72898392],
       [0.70117184, 0.56355797, 0.7482217 , 0.1451689 ],
       [0.9994954 , 0.42161074, 0.09843173, 0.29838017]])

In [65]:
a = a.ravel()

In [67]:
a.shape = (12)
a

C:\Users\hppc\AppData\Local\Temp\ipykernel_5128\4229885536.py:1: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  a.shape = (12)


array([0.53110643, 0.35485197, 0.65073548, 0.72898392, 0.70117184,
       0.56355797, 0.7482217 , 0.1451689 , 0.9994954 , 0.42161074,
       0.09843173, 0.29838017])

In [68]:
A.transpose()

array([[0.53110643, 0.70117184, 0.9994954 ],
       [0.35485197, 0.56355797, 0.42161074],
       [0.65073548, 0.7482217 , 0.09843173],
       [0.72898392, 0.1451689 , 0.29838017]])

Joining Arrays

In [70]:
A = np.ones((3, 3))
B = np.zeros((3, 3))

In [71]:
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [73]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [74]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [75]:
np.row_stack((a, b, c))

AttributeError: module 'numpy' has no attribute 'row_stack'