**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
a = np.array([[1, 2, 3]])

In [6]:
a.shape

(1, 3)

In [7]:
a.dtype

dtype('int64')

In [9]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [11]:
b.dtype

dtype('int64')

In [12]:
b.ndim

2

In [13]:
b.size

6

In [14]:
b.shape

(2, 3)

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(0,31,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])