**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

# Numpy

In [7]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

Numpy gives tremendous perfomance deference

In [5]:
a = range(0,20)
print(type(a))
list(a)

<class 'range'>


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
import numpy as np
an_arr = np.arange(20)# array
print(type(an_arr))
an_arr

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
an_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
import numpy as np
an_arr = np.arange(1000) #array
a_list = list(range(1000)) #list

In [ ]:
#a_list

In [9]:
%time for x in range(100000):an_arr2 = an_arr **2

CPU times: total: 125 ms
Wall time: 130 ms


In [ ]:
#an_arr2

In [11]:
%time for i in range(100000):a_list2 = [x**2 for x in a_list]

CPU times: total: 3.2 s
Wall time: 3.37 s


In [14]:
list1 = [2,4,8,7]
list1*5

[2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7, 2, 4, 8, 7]

In [15]:
list1+list1

[2, 4, 8, 7, 2, 4, 8, 7]

In [17]:
a = np.array(list1)
a*5

array([10, 20, 40, 35])

In [10]:
em=[]
list1=[2,3,5,6,7]
for i in list1:
       #print(i**2)
        j=i**2
        em.append(j)
print(em)

[4, 9, 25, 36, 49]


In [19]:
import numpy as np
list1=[2,3,4,5,7,8]
arr1=np.array(list1)
#arr1.dtype.int16
print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

8
6
int64
[2 3 4 5 7 8]


In [37]:
import numpy as np
list1=[2,3,4,5,7,8]
arr1=np.array(list1)

print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

arr1.dtype=np.int16
print(arr1.itemsize)
print(arr1.size)
print(arr1.dtype)
print(arr1)

8
6
int64
[2 3 4 5 7 8]
2
24
int16
[2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0 7 0 0 0 8 0 0 0]


C:\Users\hppc\AppData\Local\Temp\ipykernel_14056\188054680.py:10: DeprecationWarning: Setting the dtype on a NumPy array has been deprecated in NumPy 2.5.
Instead of changing the dtype on an array x, create a new array with x.view(new_dtype)
  arr1.dtype=np.int16


In [47]:
arr1=[2,3,4,5,7,8]

In [40]:
arr1*2

[2, 3, 4, 5, 7, 8, 2, 3, 4, 5, 7, 8]

In [41]:
arr1=np.arange(10)
print(arr1.dtype)

int64


In [42]:
print(type(arr1))

<class 'numpy.ndarray'>


In [45]:
arr1+arr1

[2, 3, 4, 5, 7, 8, 2, 3, 4, 5, 7, 8]

In [53]:
arr1 = [2,3,4,5,7,8]


In [3]:
arr1 = [2, 3, 4, 5, 7, 8]

result = [x * x for x in arr1]
print(result)

[4, 9, 16, 25, 49, 64]


In [ ]:
import numpy as np

arr1 = np.array([2, 3, 4, 5, 7, 8])

print(arr1 * arr1)

[ 4  9 16 25 49 64]
[0 0 0 0 0 0]


In [2]:
print(arr1 - arr1)

[0 0 0 0 0 0]


### Numpy ndarray - Multidimensional Array Object

In [11]:
import numpy as np
data = np.random.randn(3,3)
data

array([[-0.4384562 ,  0.17276988, -0.10924441],
       [ 1.92483562,  0.69364974,  0.1254188 ],
       [-0.68948127, -0.31601656, -1.45689218]])

In [12]:
np.random.randn(2,3,2)

array([[[ 0.81880435, -0.0088964 ],
        [ 0.62630561,  0.37031349],
        [ 0.89540392,  0.88254827]],

       [[ 1.31786243,  0.27891078],
        [ 0.22191701, -1.05484781],
        [ 0.54832635,  0.06699108]]])

In [13]:
a = np.array([[0,1,2],[4,5,6]])
a

array([[0, 1, 2],
       [4, 5, 6]])

In [4]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
import numpy as np
arr1=np.empty((5,3,2))

In [6]:
arr1

array([[[1.31644546e-311, 1.02271589e-321],
        [0.00000000e+000, 0.00000000e+000],
        [1.42413554e-306, 5.02034658e+175]],

       [[5.40725488e-038, 5.98730606e+174],
        [4.49949992e+174, 1.50400124e+161],
        [4.46596656e-062, 4.26032253e-096]],

       [[1.12855837e+277, 8.76730979e+252],
        [2.59027914e-144, 3.80985069e+180],
        [1.14428494e+243, 2.59027907e-144]],

       [[7.79952704e-143, 2.08968289e-076],
        [1.71830036e+185, 2.61887125e+180],
        [1.45298805e-051, 2.59027862e-144]],

       [[2.59903818e-144, 7.42138030e-091],
        [5.65042638e-038, 4.17824707e-062],
        [1.11475752e+261, 1.16318408e-028]]])

In [11]:
arr1=np.empty((1,2, 3, 2,2))
arr1

array([[[[[6.23042070e-307, 4.67296746e-307],
          [1.69121096e-306, 1.42419938e-306]],

         [[1.42413555e-306, 1.78019082e-306],
          [1.37959740e-306, 6.23057349e-307]],

         [[1.06811422e-306, 1.42417221e-306],
          [1.37961641e-306, 1.60220393e-306]]],


        [[[8.34424342e-308, 1.22382882e-307],
          [1.11258854e-306, 1.11261502e-306]],

         [[1.42410839e-306, 7.56597770e-307],
          [6.23059726e-307, 1.42419530e-306]],

         [[6.89805151e-307, 1.78020169e-306],
          [1.42410974e-306, 8.91238233e-313]]]]])

In [10]:
arr1.shape

(1, 2, 3, 2, 3)

In [12]:
import numpy as np
data = np.random.randn(3,3)
data

array([[ 0.28169065,  0.65954653, -0.85829028],
       [ 1.61810763, -1.99593604,  0.18273757],
       [-0.10459112,  0.49755672,  0.51297907]])

In [13]:
np.random.randn(2,3,2)

array([[[-0.25693541, -1.61712429],
        [-0.471223  ,  0.15489902],
        [-0.688455  , -0.65688962]],

       [[-0.90530979,  0.49109757],
        [ 0.10947678, -1.7880892 ],
        [-1.3392038 ,  1.30180319]]])

In [15]:
a = np.array([[0,1,2],[4,5,6]])
a

array([[0, 1, 2],
       [4, 5, 6]])

In [17]:
a = np.linspace(0,10,11)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**Array of random number**

In [20]:
np.random.randint(10,20,(3,1,3))

array([[[11, 11, 15]],

       [[12, 14, 15]],

       [[16, 13, 19]]], dtype=int32)

In [18]:
np.random.randint(0,3)

2

In [19]:
np.random.randint(1,9)

8

In [14]:
data=np.zeros((3,2))
data

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
data.shape

(3, 2)

In [16]:
type(data)

numpy.ndarray

In [17]:
data.dtype
type(data)

numpy.ndarray

In [18]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Creating ndarrays**

In [19]:
data1 = [6, 7.5, 8]
array1 = np.array(data1)
print(array1)

[6.  7.5 8. ]


In [21]:
array1.ndim

1

In [22]:
a=10
k = np.array(a)
print(k)
np.array(a).ndim

10


0

In [24]:
a=np.zeros((2,3,2,3,1))
a.ndim

5

In [25]:
array1.dtype

dtype('float64')

In [26]:
type(array1)

numpy.ndarray

In [27]:
data2 = (6, 7.5, 8, 5, 8)
arr2=np.array(data2)
arr2

array([6. , 7.5, 8. , 5. , 8. ])

In [28]:
type(arr2)

numpy.ndarray

**Array create function**
Other ways to create new arrays

In [35]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Ones

In [38]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

**Empty**

In [40]:
arr1=np.empty((2,2,2))
arr1

array([[[4.9e-324, 9.9e-324],
        [1.5e-323, 2.0e-323]],

       [[2.5e-323, 3.0e-323],
        [3.5e-323, 4.0e-323]]])

In [41]:
arr1.ndim

3

In [42]:
arr1.dtype=np.int32
arr1

C:\Users\hppc\AppData\Local\Temp\ipykernel_18252\1034947974.py:1: DeprecationWarning: Setting the dtype on a NumPy array has been deprecated in NumPy 2.5.
Instead of changing the dtype on an array x, create a new array with x.view(new_dtype)
  arr1.dtype=np.int32


array([[[1, 0, 2, 0],
        [3, 0, 4, 0]],

       [[5, 0, 6, 0],
        [7, 0, 8, 0]]], dtype=int32)

In [43]:
import numpy as np
arr1=np.empty((2, 3, 2,2))
arr1

array([[[[1.29441743e-312, 1.01855798e-312],
         [2.27053550e-312, 1.29441743e-312]],

        [[2.33419537e-312, 9.76118064e-313],
         [2.41907520e-312, 2.05833592e-312]],

        [[8.48798317e-313, 8.70018275e-313],
         [2.37663529e-312, 2.22809558e-312]]],


       [[[2.46151512e-312, 2.27053550e-312],
         [2.12199579e-313, 2.37663529e-312]],

        [[2.05833592e-312, 2.41907520e-312],
         [2.56761491e-312, 2.05833592e-312]],

        [[9.76118064e-313, 2.12199579e-312],
         [2.31297541e-312, 1.94920670e-153]]]])

In [44]:
arr1=np.empty((1,2, 3, 2,3))
arr1

array([[[[[1.05021517e-311, 1.05018876e-311, 1.42419938e-306],
          [1.42413555e-306, 1.78019082e-306, 1.37959740e-306]],

         [[6.23057349e-307, 1.06811422e-306, 1.42417221e-306],
          [1.37961641e-306, 1.60220393e-306, 8.34424342e-308]],

         [[1.22382882e-307, 1.11258854e-306, 1.11261502e-306],
          [1.42410839e-306, 7.56597770e-307, 6.23059726e-307]]],


        [[[1.42419530e-306, 1.11261027e-306, 1.24610383e-306],
          [8.45606157e-307, 6.89813979e-307, 1.33511290e-306]],

         [[1.69118787e-306, 8.06629592e-308, 1.33509185e-307],
          [8.90065533e-307, 1.27946161e-307, 8.01060542e-307]],

         [[1.05699242e-307, 1.00136897e-307, 9.45697982e-308],
          [8.90071984e-308, 1.24611470e-306, 0.00000000e+000]]]]])

In [45]:
arr1.shape

(1, 2, 3, 2, 3)

In [46]:
np.random.randint(10,20,(3,1,3)) #Array of random numbers in provided interval

array([[[10, 15, 13]],

       [[15, 15, 15]],

       [[13, 10, 11]]], dtype=int32)

In [47]:
arr1

array([[[[[1.05021517e-311, 1.05018876e-311, 1.42419938e-306],
          [1.42413555e-306, 1.78019082e-306, 1.37959740e-306]],

         [[6.23057349e-307, 1.06811422e-306, 1.42417221e-306],
          [1.37961641e-306, 1.60220393e-306, 8.34424342e-308]],

         [[1.22382882e-307, 1.11258854e-306, 1.11261502e-306],
          [1.42410839e-306, 7.56597770e-307, 6.23059726e-307]]],


        [[[1.42419530e-306, 1.11261027e-306, 1.24610383e-306],
          [8.45606157e-307, 6.89813979e-307, 1.33511290e-306]],

         [[1.69118787e-306, 8.06629592e-308, 1.33509185e-307],
          [8.90065533e-307, 1.27946161e-307, 8.01060542e-307]],

         [[1.05699242e-307, 1.00136897e-307, 9.45697982e-308],
          [8.90071984e-308, 1.24611470e-306, 0.00000000e+000]]]]])

In [48]:
arr2=np.empty(( 3, 2))
arr2

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323]])

We can also create multidimensional array using nested sequences

In [29]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
print(data2)
print(type(data2))
data2=np.array(data2)
print(data2)
print(data2.shape)
print(data2.ndim)

[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [30]:
array2 = np.array(data2)
array2.shape

(2, 4)

`ndim` and `shape` attributes give dimension and shape respectively

In [31]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8],[6,7,8,9]]
data2=np.array(data2)
data2.shape

(3, 4)

In [32]:
data2.ndim

2

In [33]:
data2.shape

(3, 4)

In [34]:
data2.dtype

dtype('int64')

In [2]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [3]:
arr1+arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
arr3 = np.vstack((arr1,arr2))
print(arr3)

print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


**Horizontal stack**

In [5]:
import numpy as np
arr3 = np.hstack((arr1,arr2))
print(arr3)

print(arr3.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)


**concating ndarray**

70. Write a program to create a 1D and 2D NumPy array using array()
• Use np.array() with lists and tuples to create ndarrays.
• Differentiate between 1D and 2D arrays by shape and nesting.
• Confirm array types using type() and ndim.

71. Write a program to explore properties of a NumPy array
• Retrieve shape, size, dtype, ndim, and itemsize attributes.
• Understand the concept of rank (number of axes).
• Explore internal buffer using the data attribute.

72. Write a program to generate a 3x3 array of zeros using zeros()
• Create arrays of predefined shapes with all zero values.
• Specify shape using tuples.
• Understand default dtype and how to override it.

73. Write a program to create a 3x3 array of ones using ones()
• Use np.ones() to initialize arrays with one-filled values.
• Generate both 1D and 2D structures.
• Compare behavior of ones() vs zeros() in different use cases.

74. Write a program to generate sequences using arange()
• Use arange(start, stop, step) to generate evenly spaced values.
• Understand integer and float-based stepping.
• Differentiate between arange() and Python’s range().

75. Write a program to reshape a 1D array into 2D using reshape()
• Apply reshape() to convert linear arrays to matrices.
• Verify dimensions and ensure reshaping is compatible with element count.
• Combine arange() and reshape() for data grid construction.

76. Write a program to create evenly spaced numbers using linspace()
• Use linspace(start, stop, num) for generating a specific number of values.
• Understand the difference between spacing and number of elements.
• Compare with arange() for use in plotting and interpolation.