**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

**Splitting Array**

In [4]:
import numpy as np
a = np.arange(20)
print('First array')
print(a)
print('\n')
print('Splitting the array in 2 equal size array')
b = np.split(a,2)
print(b)
print('\n')

First array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Splitting the array in 2 equal size array
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]




In [9]:
import numpy as np
a = np.arange(10)
print('Splitting the array: First at 3, second from 3 to 5, third from 5 to 9, remaining in fourth')
c = np.split(a, [3, 5, 9])
print(c)

Splitting the array: First at 3, second from 3 to 5, third from 5 to 9, remaining in fourth
[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([9])]


In [11]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Data types for ndarray**

In [12]:
array1 =np.array([3,4,5],dtype=float)
array1

array([3., 4., 5.])

In [13]:
array1 =np.array([3,4,5],dtype=np.float64)
array1

array([3., 4., 5.])

In [14]:
array1.dtype

dtype('float64')

In [16]:
array = np.array([1,2,3,4,5])

In [18]:
array.dtype

dtype('int64')

In [17]:
array.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [21]:
arr1 = np.array(['2.3','5.6','3.55'],dtype=np.bytes_)
arr1.dtype

dtype('S4')

In [22]:
arr1

array([b'2.3', b'5.6', b'3.55'], dtype='|S4')

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr*0.005

array([[0.005, 0.01 , 0.015],
       [0.02 , 0.025, 0.03 ]])

In [26]:
%time arr**2

CPU times: total: 15.6 ms
Wall time: 40.2 ms


array([[ 1,  4,  9],
       [16, 25, 36]])

**Comparison of Array**

In [33]:
arr2 = np.array([[3,4,5],[4,5,6]])
arr2

array([[3, 4, 5],
       [4, 5, 6]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2>arr

array([[ True,  True,  True],
       [False, False, False]])

In [36]:
arr2<arr

array([[False, False, False],
       [False, False, False]])

In [37]:
7<6

False

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr<=4

array([[ True,  True,  True],
       [ True, False, False]])